spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      maxRequestSize: 1GB
      maxFileSize: 1GB
  redis:
    host: 127.0.0.1
    port: 6379
    password:

upload:
  path: /path/blog/