spring:
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: 5000MB
      maxRequestSize: 5000MB
mybatis-plus:
  mapper-locations: classpath*:com/example/project/**/xml/*.xml
  globalConfig:
    dbConfig:
      logicDeleteField: deleted
      logicDeleteValue: 1
      logicNotDeleteValue: 0
  configuration:
    mapUnderscoreToCamelCase: true
    cacheEnabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

token:
  header: Authoiorization
  expireTime: 30
  secret: dawndawndawn